application: colofwords
version: 1
api_version: 1
runtime: python

handlers:
- url: /static
  static_dir: static

- url: /
  script: colorofwords.py 

- url: /api
  script: api.py 
  
- url: /lasagna
  script: lasagna.py

- url: /beta.*
  script: beta.py
